//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSCardService.SCardService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SHARE", Namespace="http://schemas.datacontract.org/2004/07/GemCard")]
    public enum SHARE : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exclusive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shared = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Direct = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PROTOCOL", Namespace="http://schemas.datacontract.org/2004/07/GemCard")]
    public enum PROTOCOL : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        T0 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        T1 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Raw = 65536,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = -2147483648,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        T0orT1 = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DISCONNECT", Namespace="http://schemas.datacontract.org/2004/07/GemCard")]
    public enum DISCONNECT : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Leave = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reset = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unpower = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eject = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APDUCommand", Namespace="http://schemas.datacontract.org/2004/07/GemCard.Service")]
    [System.SerializableAttribute()]
    public partial class APDUCommand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte InsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte LeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte P1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte P2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Class {
            get {
                return this.ClassField;
            }
            set {
                if ((this.ClassField.Equals(value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Ins {
            get {
                return this.InsField;
            }
            set {
                if ((this.InsField.Equals(value) != true)) {
                    this.InsField = value;
                    this.RaisePropertyChanged("Ins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Le {
            get {
                return this.LeField;
            }
            set {
                if ((this.LeField.Equals(value) != true)) {
                    this.LeField = value;
                    this.RaisePropertyChanged("Le");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte P1 {
            get {
                return this.P1Field;
            }
            set {
                if ((this.P1Field.Equals(value) != true)) {
                    this.P1Field = value;
                    this.RaisePropertyChanged("P1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte P2 {
            get {
                return this.P2Field;
            }
            set {
                if ((this.P2Field.Equals(value) != true)) {
                    this.P2Field = value;
                    this.RaisePropertyChanged("P2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APDUResponse", Namespace="http://schemas.datacontract.org/2004/07/GemCard.Service")]
    [System.SerializableAttribute()]
    public partial class APDUResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SW1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SW2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SW1 {
            get {
                return this.SW1Field;
            }
            set {
                if ((this.SW1Field.Equals(value) != true)) {
                    this.SW1Field = value;
                    this.RaisePropertyChanged("SW1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SW2 {
            get {
                return this.SW2Field;
            }
            set {
                if ((this.SW2Field.Equals(value) != true)) {
                    this.SW2Field = value;
                    this.RaisePropertyChanged("SW2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SCardService.IRemoteCard")]
    public interface IRemoteCard {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteCard/ListReaders", ReplyAction="http://tempuri.org/IRemoteCard/ListReadersResponse")]
        string[] ListReaders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteCard/Connect", ReplyAction="http://tempuri.org/IRemoteCard/ConnectResponse")]
        void Connect(string Reader, TestSCardService.SCardService.SHARE ShareMode, TestSCardService.SCardService.PROTOCOL PreferredProtocols);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteCard/Disconnect", ReplyAction="http://tempuri.org/IRemoteCard/DisconnectResponse")]
        void Disconnect(TestSCardService.SCardService.DISCONNECT Disposition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteCard/Transmit", ReplyAction="http://tempuri.org/IRemoteCard/TransmitResponse")]
        TestSCardService.SCardService.APDUResponse Transmit(TestSCardService.SCardService.APDUCommand ApduCmd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteCard/BeginTransaction", ReplyAction="http://tempuri.org/IRemoteCard/BeginTransactionResponse")]
        void BeginTransaction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteCard/EndTransaction", ReplyAction="http://tempuri.org/IRemoteCard/EndTransactionResponse")]
        void EndTransaction(TestSCardService.SCardService.DISCONNECT Disposition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteCard/GetAttribute", ReplyAction="http://tempuri.org/IRemoteCard/GetAttributeResponse")]
        byte[] GetAttribute(uint AttribId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRemoteCardChannel : TestSCardService.SCardService.IRemoteCard, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteCardClient : System.ServiceModel.ClientBase<TestSCardService.SCardService.IRemoteCard>, TestSCardService.SCardService.IRemoteCard {
        
        public RemoteCardClient() {
        }
        
        public RemoteCardClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteCardClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteCardClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteCardClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ListReaders() {
            return base.Channel.ListReaders();
        }
        
        public void Connect(string Reader, TestSCardService.SCardService.SHARE ShareMode, TestSCardService.SCardService.PROTOCOL PreferredProtocols) {
            base.Channel.Connect(Reader, ShareMode, PreferredProtocols);
        }
        
        public void Disconnect(TestSCardService.SCardService.DISCONNECT Disposition) {
            base.Channel.Disconnect(Disposition);
        }
        
        public TestSCardService.SCardService.APDUResponse Transmit(TestSCardService.SCardService.APDUCommand ApduCmd) {
            return base.Channel.Transmit(ApduCmd);
        }
        
        public void BeginTransaction() {
            base.Channel.BeginTransaction();
        }
        
        public void EndTransaction(TestSCardService.SCardService.DISCONNECT Disposition) {
            base.Channel.EndTransaction(Disposition);
        }
        
        public byte[] GetAttribute(uint AttribId) {
            return base.Channel.GetAttribute(AttribId);
        }
    }
}
